### ISSUE TITLE
URL to device is invalid

### ISSUE THREAD

**Issue by smeusekentik** [ishakmuhamad/contactless-water-level#1]
Hey, thanks for posting this, i want to try it for my automated chicken watering system. The link for the actual device seems to be invalid, could you post the device make/model?

**Comment by ishakmuhamad** [comment]
Please try this new link at Ali Express...

Just found this amazing item on AliExpress. Check it out! MYR13.69  14%OFF | XKC-Y25 Non-Contact Liquid Level Sensor Tank Water Level Sensor Water Level Sensor Liquid Induction Switch
https://a.aliexpress.com/_okMJRIk

Or you can Google it... non contact water level sensor.

**Comment by smeusekentik** [comment]
Thank you, I did google it, but wasn't exactly sure. Thanks!
